# -*- coding: utf-8 -*-

from __future__ import division, print_function, unicode_literals


WS_NFSE_ENVIO_LOTE = 0
WS_NFSE_CONSULTA_LOTE = 1
WS_NFSE_CANCELAMENTO = 2
WS_NFSE_CONSULTA_NOTA = 3
WS_NFSE_CONSULTA_NFSERPS = 4
WS_NFSE_CONSULTA_SEQUENCIA_RPS = 5

NFSE_AMBIENTE_PRODUCAO = 1
NFSE_AMBIENTE_HOMOLOGACAO = 2

#
# Códigos SIAFI
#
SIAFI_SOROCABA_SP = 7145
SIAFI_CAMPINAS_SP = 6291
SIAFI_UBERLANDIA_MG = 5403
SIAFI_TERESINA_PI = 1219
SIAFI_BELEM_PA = 427
SIAFI_NOVA_IGUACU_RJ = 5869
SIAFI_SAO_LUIS_MA = 921
SIAFI_CAMPO_GRANDE_MS = 9051
