# -*- coding: utf-8 -*-

WS_CTE_RECEPCAO  = 0
WS_CTE_RET_RECEPCAO  = 1
WS_CTE_INUTILIZACAO  = 2
WS_CTE_CONSULTA  = 3
WS_CTE_STATUS_SERVICO = 4
WS_CTE_EVENTO  = 5
WS_CTE_CONSULTA_CADASTRO  = 6

#WS_DPEC_RECEPCAO = 7
#WS_DPEC_CONSULTA = 8

WS_NFE_RECEPCAO_EVENTO = 9
#WS_NFE_DOWNLOAD = 10
#WS_NFE_CONSULTA_DESTINADAS = 11
WS_DFE_DISTRIBUICAO = 12


CTE_AMBIENTE_PRODUCAO    = 1
CTE_AMBIENTE_HOMOLOGACAO = 2
